yml update 1.3

diff --git a/.github/workflows/github-tests.yml b/.github/workflows/github-tests.yml
--- a/.github/workflows/github-tests.yml
+++ b/.github/workflows/github-tests.yml
@@ -33,15 +33,17 @@ jobs:
           path: ~/.m2
           key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
           restore-keys: |
-            ${{ runner.os }}-maven
+            ${{ runner.os }}-maven   
 
       - name: Build and run tests
         run: mvn clean test
+
+      - name: List files in AutomationReport
+        run: ls -R AutomationReport || echo "Directory not found"
 
       - name: Upload Test Reports
         if: always()
         uses: actions/upload-artifact@v4
         with:
-          name: ExtentReports
-          path: |
-            AutomationReport/ExtentReport_*.html
+          name: DebugReports
+          path: '**/*.html'
